language: node_js
node_js:
  - "8"

after_success:
  - npm i coveralls
  - cat ./test/unit/coverage/lcov.info | coveralls

before_deploy:
  - npm run build-storybook
  - npm run build

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
  - provider: npm
    skip-cleanup: true
    email: "nicholaslee119@gmail.com"
    api_key: $NPM_TOKEN
    tag: next
    on:
      tags: true    