language: node_js
node_js:
  - "7"

after_success:
  - npm i coveralls
  - cat ./test/unit/coverage/lcov.info | coveralls

deploy:
provider: pages
skip-cleanup: true
github-token: $GITHUB_TOKEN
keep-history: true
on:
  branch: gh-pages